# Generated by Django 6.0.3 on 2026-03-14 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('MOVIE', 'Movies'), ('SERIES', 'Series'), ('ANIME', 'Anime'), ('ANIMATION', 'Animation')], max_length=20)),
                ('type', models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'Series')], max_length=20)),
                ('genre', models.CharField(blank=True, default='', max_length=160)),
                ('studio', models.CharField(blank=True, default='', max_length=160)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2200)])),
                ('platform', models.CharField(blank=True, default='', max_length=120)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Movie duration in minutes.', null=True)),
                ('total_seasons', models.PositiveIntegerField(default=1)),
                ('total_episodes', models.PositiveIntegerField(default=1)),
                ('episode_duration', models.PositiveIntegerField(blank=True, help_text='Episode duration in minutes.', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('WATCHING', 'Watching'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('current_season', models.PositiveIntegerField(default=1)),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('date_watched', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 10.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='media_tracker.mediaitem')),
            ],
            options={
                'ordering': ['-date_watched', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['category', 'type', 'status'], name='media_track_categor_32d9be_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['platform'], name='media_track_platfor_c429c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['year'], name='media_track_year_86fb04_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprogress',
            index=models.Index(fields=['date_watched'], name='media_track_date_wa_44497b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprogress',
            index=models.Index(fields=['completed'], name='media_track_complet_50df6a_idx'),
        ),
    ]
