# Generated by Django 4.2.11 on 2026-03-06 20:06

import apps.education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(choices=[('transcript', 'Transcript'), ('certificate', 'Certificate'), ('identity', 'Identity'), ('other', 'Other')], max_length=30)),
                ('version', models.CharField(blank=True, default='v1', max_length=40)),
                ('file', models.FileField(upload_to=apps.education.models.education_document_path)),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=180)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=60)),
                ('study_hours', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(max_length=120)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='discovered', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
