# Generated by Django 4.2.11 on 2026-03-06 20:06

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('date', models.DateField()),
                ('content', apps.common.fields.EncryptedTextField()),
                ('mood', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
