# Generated by Django 4.2.11 on 2026-03-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'created_at'), name='unique_diary_snapshot'),
        ),
    ]
