# Generated by Django 4.2.11 on 2026-03-06 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('movie', 'Movies'), ('series', 'Series'), ('anime', 'Anime'), ('animation', 'Animation')], max_length=20)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=20)),
                ('genre', models.CharField(blank=True, default='', max_length=180)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Movie duration in minutes.', null=True)),
                ('total_seasons', models.PositiveIntegerField(default=1)),
                ('total_episodes', models.PositiveIntegerField(default=1)),
                ('episode_duration', models.PositiveIntegerField(blank=True, help_text='Episode duration in minutes.', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('watching', 'Watching'), ('completed', 'Completed')], default='planned', max_length=20)),
            ],
            options={
                'ordering': ['-date_added', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='media.mediaitem')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MediaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('current_season', models.PositiveIntegerField(default=1)),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('watched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='media.mediaitem')),
            ],
            options={
                'ordering': ['-watched_at', '-created_at'],
            },
        ),
    ]
