# Generated by Django 4.2.11 on 2026-03-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media.season'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('media_item', 'number')},
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['user', 'category', 'type', 'status'], name='media_media_user_id_37f215_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['user', 'year'], name='media_media_user_id_611619_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number')},
        ),
    ]
