# Generated by Django 4.2.11 on 2026-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/covers/'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='studio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
