# Generated by Django 4.2.11 on 2026-03-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_event', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('PROJECT_CREATED', 'Project Created'), ('TASK_COMPLETED', 'Task Completed'), ('TRANSACTION_ADDED', 'Transaction Added'), ('MEDIA_WATCHED', 'Media Watched'), ('DIARY_ENTRY_CREATED', 'Diary Entry Created'), ('BUCKET_ITEM_COMPLETED', 'Bucket Item Completed'), ('SCHOLARSHIP_APPLIED', 'Scholarship Applied')], max_length=100)),
                ('condition', models.TextField(blank=True, default='')),
                ('action', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['trigger_event', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('PROJECT_CREATED', 'Project Created'), ('TASK_COMPLETED', 'Task Completed'), ('TRANSACTION_ADDED', 'Transaction Added'), ('MEDIA_WATCHED', 'Media Watched'), ('DIARY_ENTRY_CREATED', 'Diary Entry Created'), ('BUCKET_ITEM_COMPLETED', 'Bucket Item Completed'), ('SCHOLARSHIP_APPLIED', 'Scholarship Applied')], db_index=True, max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
