"""
Django settings for myos_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import mimetypes
import os
import sys
from pathlib import Path
from urllib.parse import urlparse

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure common static file types resolve correctly in minimal images/hosts.
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("image/svg+xml", ".svg", True)


env = environ.Env()
# Prefer the repo-local `.env` over unrelated shell defaults so local runs and
# tests behave the same way as the checked-in project configuration.
environ.Env.read_env(BASE_DIR / ".env", overwrite=True)


def _database_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme in {'postgres', 'postgresql'}:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/') or 'myos',
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or '127.0.0.1',
            'PORT': str(parsed.port or '5432'),
            'CONN_MAX_AGE': 60,
        }
    if parsed.scheme == 'sqlite':
        sqlite_path = parsed.path or '/db.sqlite3'
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }
    raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')


def _postgres_backend_available():
    return any(
        importlib.util.find_spec(module_name) is not None
        for module_name in ('psycopg', 'psycopg2')
    )


def _module_available(module_name):
    return importlib.util.find_spec(module_name) is not None


def _sqlite_database_config():
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default=os.getenv("DJANGO_SECRET_KEY", "unsafe-dev-secret-key"))
SECRET_KEY_FALLBACKS = env.list("SECRET_KEY_FALLBACKS", default=[])

# Default to debug in local development so Django serves app static assets.
# Production should explicitly set `DJANGO_DEBUG=0`.
DEBUG = env.bool("DEBUG", default=False)

default_hosts = ["127.0.0.1", "localhost", "testserver"]
legacy_hosts = os.getenv("DJANGO_ALLOWED_HOSTS")
if legacy_hosts:
    default_hosts = [host.strip() for host in legacy_hosts.split(",") if host.strip()]
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=default_hosts)
if DEBUG or "test" in sys.argv:
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, "127.0.0.1", "localhost", "testserver"]))
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "accounts",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myos_app',
    'media_tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if _module_available('whitenoise.middleware'):
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'myos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myos_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = env("DATABASE_URL", default="")
if DATABASE_URL:
    database_config = _database_config_from_url(DATABASE_URL)
    if database_config.get('ENGINE') == 'django.db.backends.postgresql' and _postgres_backend_available():
        database_config['CONN_MAX_AGE'] = 60
    elif database_config.get('ENGINE') == 'django.db.backends.postgresql':
        database_config = _sqlite_database_config()
    DATABASES = {'default': database_config}
else:
    if _postgres_backend_available():
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env("DATABASE_NAME", default="myos_db"),
                'USER': env("DATABASE_USER", default="immanuel"),
                'PASSWORD': env("DATABASE_PASSWORD", default=""),
                'HOST': env("DATABASE_HOST", default="127.0.0.1"),
                'PORT': env("DATABASE_PORT", default="5432"),
            }
        }
    else:
        DATABASES = {'default': _sqlite_database_config()}

AUTH_USER_MODEL = "accounts.User"

# Email settings — configure with your actual SMTP provider
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default=env("EMAIL_APP_PASSWORD", default=""))
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default=(f"MyOS <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else "myos@localhost"),
)
MYOS_NOTIFICATION_EMAIL = env("MYOS_NOTIFICATION_EMAIL", default="")
MYOS_REMINDER_EMAIL_RECIPIENT = env("MYOS_REMINDER_EMAIL_RECIPIENT", default=MYOS_NOTIFICATION_EMAIL)
MYOS_REMINDER_EMAIL_LOOKAHEAD_DAYS = env.int("MYOS_REMINDER_EMAIL_LOOKAHEAD_DAYS", default=1)
LOGIN_RATE_LIMIT_ATTEMPTS = env.int("LOGIN_RATE_LIMIT_ATTEMPTS", default=10)
LOGIN_RATE_LIMIT_WINDOW_SECONDS = env.int("LOGIN_RATE_LIMIT_WINDOW_SECONDS", default=300)
DIARY_PAGE_SIZE = env.int("DIARY_PAGE_SIZE", default=20)
SEARCH_MIN_QUERY_LENGTH = env.int("SEARCH_MIN_QUERY_LENGTH", default=2)
SEARCH_RESULT_LIMIT = env.int("SEARCH_RESULT_LIMIT", default=20)

# Sessions — secure HttpOnly cookies
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SAMESITE = "Strict"
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=1209600)
SESSION_SAVE_EVERY_REQUEST = True
REMEMBER_ME_AGE = env.int("REMEMBER_ME_AGE", default=1209600)
SHORT_SESSION_AGE = env.int("SHORT_SESSION_AGE", default=3600)

# CSRF
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SAMESITE = "Strict"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "myos-cache",
    }
}

OTP_EXPIRY_SECONDS = env.int("OTP_EXPIRY_SECONDS", default=600)

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'myos_app' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
if _module_available('whitenoise.storage'):
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

SECURE_REFERRER_POLICY = "same-origin"

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# To auto-process recurring transactions, add to your crontab:
# 0 6 * * * cd /path/to/myos_project && python manage.py process_recurring
# Or call it from a startup script / systemd timer.
