# Generated by Django 4.2.11 on 2026-03-06 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_bucket_item_users_and_counts(apps, schema_editor):
    BucketCategory = apps.get_model("bucket", "BucketCategory")
    BucketItem = apps.get_model("bucket", "BucketItem")

    category_defaults = {
        "Travel": ("fa-plane", "blue"),
        "Achievements": ("fa-trophy", "yellow"),
        "Experiences": ("fa-compass", "orange"),
        "Learning": ("fa-book", "green"),
        "Wealth": ("fa-coins", "brown"),
    }

    for category in BucketCategory.objects.select_related("user"):
        default_icon, default_color = category_defaults.get(category.name, ("", category.color or ""))
        item_qs = BucketItem.objects.filter(category=category)
        item_qs.update(user=category.user)
        category.icon = category.icon or default_icon
        category.color = category.color or default_color
        category.item_count = item_qs.count()
        category.completed_count = item_qs.filter(status="completed").count()
        category.save(update_fields=["icon", "color", "item_count", "completed_count"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("bucket", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketcategory",
            name="completed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bucketcategory",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="bucketcategory",
            name="item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bucketitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("idea", "Idea"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_bucket_item_users_and_counts, noop_reverse),
        migrations.AlterField(
            model_name="bucketitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
