from django.urls import path
from myos_app import views

urlpatterns = [
    path("", views.dashboard_page, name="dashboard"),
    path("home/", views.home, name="home"),
    path("personal/", views.personal_page, name="personal"),
    path("education/", views.education_page, name="education"),
    path("finance/", views.finance_page, name="finance"),
    path("bucket/", views.bucket_list, name="bucket"),
    path("bucket-list/", views.bucket_list, name="bucket_list"),
    path("bucket-list/add/", views.add_bucket_goal, name="add_bucket_goal"),
    path("bucket-list/edit/<int:id>/", views.edit_bucket_goal, name="edit_bucket_goal"),
    path("bucket-list/delete/<int:id>/", views.delete_bucket_goal, name="delete_bucket_goal"),
    path("bucket-list/category/<str:category>/", views.bucket_category, name="bucket_category"),
    path("projects/", views.projects_page, name="projects"),
    path("diary/", views.diary_page, name="diary"),
    path("reminders/", views.reminders_page, name="reminders"),
    path("calendar/", views.calendar_page, name="calendar"),
    path("notifications/", views.notifications_page, name="notifications"),
    path("settings/", views.settings_page, name="settings"),

    path("api/projects/", views.projects_list, name="projects_list"),
    path("api/projects/create/", views.projects_create, name="projects_create"),
    path("api/projects/<int:project_id>/update/", views.projects_update, name="projects_update"),
    path("api/projects/<int:project_id>/delete/", views.projects_delete, name="projects_delete"),

    path("api/bootstrap/", views.bootstrap_data, name="bootstrap_data"),
    path("api/search/", views.global_search, name="global_search"),
    path("api/calendar/events/", views.calendar_events, name="calendar_events"),
    path("api/tasks/create/", views.create_task, name="create_task"),
    path("api/tasks/<int:task_id>/toggle/", views.toggle_task, name="toggle_task"),
    path("api/reminders/bootstrap/", views.reminders_bootstrap, name="reminders_bootstrap"),
    path("api/reminders/create/", views.reminders_create, name="reminders_create"),
    path("api/reminders/<int:reminder_id>/update/", views.reminders_update, name="reminders_update"),
    path("api/reminders/<int:reminder_id>/toggle/", views.reminders_toggle, name="reminders_toggle"),
    path("api/reminders/<int:reminder_id>/delete/", views.reminders_delete, name="reminders_delete"),
    path("api/diary/save/", views.save_diary_entry, name="save_diary_entry"),
    path("api/diary/streak/", views.diary_streak, name="diary_streak"),
    path("api/diary/entries/", views.diary_entries_list, name="diary_entries_list"),
    path("api/diary/export/", views.diary_export_csv, name="diary_export"),
    path("api/export/all/", views.full_data_export, name="full_data_export"),
    path("api/profile/save/", views.save_profile, name="save_profile"),
    path("api/notifications/save/", views.save_notifications, name="save_notifications"),
    path("api/notifications/", views.notifications_feed, name="notifications_feed"),
    path("api/notifications/mark-all-read/", views.notifications_mark_all_read, name="notifications_mark_all_read"),
    path("api/notifications/<slug:notification_id>/mark-read/", views.notifications_mark_read, name="notifications_mark_read"),
    path("api/forms/<slug:page_slug>/", views.get_page_form_data, name="get_page_form_data"),
    path("api/forms/<slug:page_slug>/save/", views.save_page_form_data, name="save_page_form_data"),
    path("api/uploads/<slug:page_slug>/", views.list_uploaded_files, name="list_uploaded_files"),
    path("api/uploads/<slug:page_slug>/<slug:field_key>/", views.upload_file_for_field, name="upload_file_for_field"),

    path("api/personal-vault/bootstrap/", views.personal_vault_bootstrap, name="personal_vault_bootstrap"),
    path("api/personal-vault/step1/save/", views.personal_vault_step1_save, name="personal_vault_step1_save"),
    path("api/personal-vault/step2/save/", views.personal_vault_step2_save, name="personal_vault_step2_save"),
    path("api/personal-vault/step3/save/", views.personal_vault_step3_save, name="personal_vault_step3_save"),
    path("api/personal-vault/identity-files/", views.personal_vault_identity_files, name="personal_vault_identity_files"),
    path("api/personal-vault/identity-files/upload/", views.personal_vault_identity_file_upload, name="personal_vault_identity_file_upload"),
    path("api/personal-vault/identity-files/<int:file_id>/delete/", views.personal_vault_identity_file_delete, name="personal_vault_identity_file_delete"),
    path("api/personal-vault/digital-accounts/", views.personal_vault_digital_accounts, name="personal_vault_digital_accounts"),
    path("api/personal-vault/digital-accounts/create/", views.personal_vault_digital_accounts_create, name="personal_vault_digital_accounts_create"),
    path("api/personal-vault/digital-accounts/<int:account_id>/update/", views.personal_vault_digital_accounts_update, name="personal_vault_digital_accounts_update"),
    path("api/personal-vault/digital-accounts/<int:account_id>/delete/", views.personal_vault_digital_accounts_delete, name="personal_vault_digital_accounts_delete"),
    path("api/personal-vault/social-profiles/save/", views.personal_vault_social_profiles_save, name="personal_vault_social_profiles_save"),
    path("api/personal-vault/password-references/", views.personal_vault_password_references, name="personal_vault_password_references"),
    path("api/personal-vault/password-references/create/", views.personal_vault_password_references_create, name="personal_vault_password_references_create"),
    path("api/personal-vault/password-references/<int:reference_id>/update/", views.personal_vault_password_references_update, name="personal_vault_password_references_update"),
    path("api/personal-vault/password-references/<int:reference_id>/delete/", views.personal_vault_password_references_delete, name="personal_vault_password_references_delete"),

    path("api/finance/bootstrap/", views.finance_bootstrap, name="finance_bootstrap"),

    path("api/finance/transactions/", views.finance_transactions, name="finance_transactions"),
    path("api/finance/transactions/create/", views.finance_transactions_create, name="finance_transactions_create"),
    path("api/finance/transactions/<int:transaction_id>/update/", views.finance_transactions_update, name="finance_transactions_update"),
    path("api/finance/transactions/<int:transaction_id>/delete/", views.finance_transactions_delete, name="finance_transactions_delete"),
    path("api/finance/transactions/export.csv", views.finance_transactions_export_csv, name="finance_transactions_export_csv"),

    path("api/finance/categories/", views.finance_categories, name="finance_categories"),
    path("api/finance/categories/create/", views.finance_categories_create, name="finance_categories_create"),
    path("api/finance/categories/<int:category_id>/update/", views.finance_categories_update, name="finance_categories_update"),
    path("api/finance/categories/<int:category_id>/delete/", views.finance_categories_delete, name="finance_categories_delete"),

    path("api/finance/budgets/", views.finance_budgets, name="finance_budgets"),
    path("api/finance/budgets/create/", views.finance_budgets_create, name="finance_budgets_create"),
    path("api/finance/budgets/<int:budget_id>/update/", views.finance_budgets_update, name="finance_budgets_update"),
    path("api/finance/budgets/<int:budget_id>/delete/", views.finance_budgets_delete, name="finance_budgets_delete"),

    path("api/finance/savings-goals/", views.finance_savings_goals, name="finance_savings_goals"),
    path("api/finance/savings-goals/create/", views.finance_savings_goals_create, name="finance_savings_goals_create"),
    path("api/finance/savings-goals/<int:goal_id>/update/", views.finance_savings_goals_update, name="finance_savings_goals_update"),
    path("api/finance/savings-goals/<int:goal_id>/delete/", views.finance_savings_goals_delete, name="finance_savings_goals_delete"),

    path("api/finance/application-costs/", views.finance_application_costs, name="finance_application_costs"),
    path("api/finance/application-costs/create/", views.finance_application_costs_create, name="finance_application_costs_create"),
    path("api/finance/application-costs/<int:cost_id>/update/", views.finance_application_costs_update, name="finance_application_costs_update"),
    path("api/finance/application-costs/<int:cost_id>/delete/", views.finance_application_costs_delete, name="finance_application_costs_delete"),

    path("api/finance/project-budgets/", views.finance_project_budgets, name="finance_project_budgets"),
    path("api/finance/project-budgets/create/", views.finance_project_budgets_create, name="finance_project_budgets_create"),
    path("api/finance/project-budgets/<int:project_budget_id>/update/", views.finance_project_budgets_update, name="finance_project_budgets_update"),
    path("api/finance/project-budgets/<int:project_budget_id>/delete/", views.finance_project_budgets_delete, name="finance_project_budgets_delete"),

    path("api/finance/recurring/", views.finance_recurring, name="finance_recurring"),
    path("api/finance/recurring/create/", views.finance_recurring_create, name="finance_recurring_create"),
    path("api/finance/recurring/<int:recurring_id>/update/", views.finance_recurring_update, name="finance_recurring_update"),
    path("api/finance/recurring/<int:recurring_id>/delete/", views.finance_recurring_delete, name="finance_recurring_delete"),
    path("api/finance/forecast/", views.finance_forecast, name="finance_forecast"),
    path("api/finance/recurring/<int:recurring_id>/apply-now/", views.finance_recurring_apply_now, name="finance_recurring_apply_now"),

    path("api/finance/alerts/", views.finance_alerts, name="finance_alerts"),
    path("api/finance/alerts/<int:alert_id>/mark-read/", views.finance_alert_mark_read, name="finance_alert_mark_read"),
    path("api/finance/alerts/mark-all-read/", views.finance_alert_mark_all_read, name="finance_alert_mark_all_read"),

    path("api/education/bootstrap/", views.education_bootstrap, name="education_bootstrap"),

    path("api/education/levels/", views.education_levels, name="education_levels"),
    path("api/education/levels/create/", views.education_levels_create, name="education_levels_create"),
    path("api/education/levels/<int:level_id>/update/", views.education_levels_update, name="education_levels_update"),
    path("api/education/levels/<int:level_id>/delete/", views.education_levels_delete, name="education_levels_delete"),

    path("api/education/exams/", views.education_exams, name="education_exams"),
    path("api/education/exams/create/", views.education_exams_create, name="education_exams_create"),
    path("api/education/exams/<int:exam_id>/update/", views.education_exams_update, name="education_exams_update"),
    path("api/education/exams/<int:exam_id>/delete/", views.education_exams_delete, name="education_exams_delete"),

    path("api/education/documents/", views.education_documents, name="education_documents"),
    path("api/education/documents/create/", views.education_documents_create, name="education_documents_create"),
    path("api/education/documents/<int:document_id>/update/", views.education_documents_update, name="education_documents_update"),
    path("api/education/documents/<int:document_id>/delete/", views.education_documents_delete, name="education_documents_delete"),

    path("api/education/scholarships/", views.education_scholarships, name="education_scholarships"),
    path("api/education/scholarships/create/", views.education_scholarships_create, name="education_scholarships_create"),
    path("api/education/scholarships/<int:scholarship_id>/update/", views.education_scholarships_update, name="education_scholarships_update"),
    path("api/education/scholarships/<int:scholarship_id>/delete/", views.education_scholarships_delete, name="education_scholarships_delete"),

    path("api/education/requirements/create/", views.education_requirements_create, name="education_requirements_create"),
    path("api/education/requirements/<int:requirement_id>/update/", views.education_requirements_update, name="education_requirements_update"),
    path("api/education/requirements/<int:requirement_id>/delete/", views.education_requirements_delete, name="education_requirements_delete"),
    path("api/education/requirements/<int:requirement_id>/toggle/", views.education_requirements_toggle, name="education_requirements_toggle"),

    path("api/education/applications/create/", views.education_applications_create, name="education_applications_create"),
    path("api/education/applications/<int:application_id>/update/", views.education_applications_update, name="education_applications_update"),
    path("api/education/applications/<int:application_id>/delete/", views.education_applications_delete, name="education_applications_delete"),

    path("api/education/deadline-alerts/", views.education_deadline_alerts, name="education_deadline_alerts"),
]
